name: test

on:
  workflow_dispatch:
  push:

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
      - name: Step is going to pass
        run: echo Passing step

      - name: Step is going to fail
        run: exit 1
        continue-on-error: true

      - name: Step To run on failure
        if: ${{ failure() }}
        run: echo "executed"
      - name: Run last
        run: echo "I'm running"