name: test

on:
  workflow_dispatch:
  push:

jobs:
  FailJobIssueDemo:
    runs-on: self-hosted
    steps:
      - name: Step is going to pass
        run: aws eks --region us-east-1 update-kubeconfig --name kor-dev-cluster --profile dev

